- projects/README.md
- projects/distribution/.gitignore
- projects/kubernetes/.gitignore
- projects/runc/.gitignore
Signed-off-by: David Korczynski <david@adalogics.com>
> init project folder

- projects/kubernetes/aes_fuzzer.go
- projects/kubernetes/apiextensions_fuzzer.go
- projects/kubernetes/apiserver_fuzzer.go
- projects/kubernetes/build.sh
- projects/kubernetes/converter_fuzzer.go
- projects/kubernetes/deepcopy_fuzzer.go
- projects/kubernetes/gofuzz-fuzzers.go
- projects/kubernetes/internal_kubelet_fuzzer.go
- projects/kubernetes/internal_kubelet_kuberuntime_fuzzer.go
- projects/kubernetes/internal_kubelet_server_fuzzer.go
- projects/kubernetes/kubectl_fuzzer.go
- projects/kubernetes/kubelet_fuzzer.go
- projects/kubernetes/parser_fuzzer.go
- projects/kubernetes/roundtrip_fuzzer.go
- projects/kubernetes/scheduler_fuzzer.go
- projects/kubernetes/validation_fuzzer.go
Adds new fuzzers for Kubernetes.
> Kubernetes: Add new fuzzers

- projects/kubernetes/README.md
- projects/kubernetes/autogenerate.py
- projects/kubernetes/build.sh
Adds a script that autogenerates a fuzzer for all the protobuf marshaling apis.
> Kubernetes: Add api_marshaling_fuzzer

- README.md
Initial documentation. The goal is to provide guidance for CNCF project devs on how to integrate fuzzing into their projects
> update frontpage with documentation

- projects/linkerd2/build.sh
- projects/linkerd2/destination_fuzzer.go
- projects/linkerd2/fuzzers.go
- projects/linkerd2/healthcheck_fuzzer.go
- projects/linkerd2/identity_fuzzer.go
- projects/linkerd2/inject_fuzzer.go
Moves over fuzzers from https://github.com/google/oss-fuzz/tree/master/projects/linkerd2
> Linkerd2: Move fuzzers here from OSS-fuzz

- projects/etcd/build.sh
- projects/etcd/raft_api_fuzzer.go
- projects/etcd/raft_fuzzer.go
- projects/etcd/v2auth_fuzzer.go
- projects/etcd/v3_grpc_fuzzer.go
Adds 6 new fuzzers for etcd and a build script so they can run on OSS-fuzz
> etcd: Add first fuzzers

- projects/runc/build.sh
- projects/runc/intelrdt_fuzzer.go
Refactors the intelrdt fuzzer.
> runc: Refactor

- projects/etcd/build.sh
- projects/etcd/store_fuzzer.go
Adds a fuzzer for `server/auth`.
> etcd: Add server auth fuzzer

- projects/kubernetes/apiserver_fuzzer.go
Switches from `f.GenerateStruct` which sets all fields to setting `DryRun` and `FieldManager`  manually.
> kubernetes registry fuzzer: ignore FieldValidation field

- projects/etcd/build.sh
- projects/etcd/grpc_proxy_fuzzer.go
Adds a fuzzer for the https://github.com/etcd-io/etcd/tree/main/server/proxy/grpcproxy package.
> etcd: Add grpc proxy fuzzer

- projects/etcd/grpc_proxy_fuzzer.go
- projects/etcd/v3_grpc_fuzzer.go
check_build is currently broken. This fixes the issue.
OSS-fuzz issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43405
> etcd fix broken check_build

- projects/argo/ancestry_fuzzer.go
- projects/argo/argo-cd_db_fuzzer.go
- projects/argo/argo-cd_rbac_fuzzer.go
- projects/argo/argo-cd_resource_tracking_fuzzer.go
- projects/argo/argo-cd_util_grpc_fuzzer.go
- projects/argo/argo-cd_validate_project_fuzzer.go
- projects/argo/artifacts_fuzzer.go
- projects/argo/build.sh
- projects/argo/gpg_fuzzer.go
- projects/argo/operator_fuzzer.go
- projects/argo/workflows_sso_fuzzer.go
- projects/argo/workflows_sync_fuzzer.go
Adds more fuzzers to increase fuzz coverage
> ago: Add more coverage

- projects/containerd/build.sh
- projects/containerd/cri_fuzzer2.go
- projects/containerd/diff_fuzzer.go
- projects/containerd/docker_fuzzer_internal.go
- projects/containerd/exchange_fuzzer.go
- projects/containerd/fuzz_images.go
- projects/containerd/remotes_docker_fuzzer.go
- projects/containerd/uuid_fuzzer.go
> containerd: Add fuzzers

- projects/etcd/etcdserver_fuzzer.go
Helps the fuzzer progress past https://github.com/etcd-io/etcd/blob/3c77c7fd3c5bcfda918f005497eedcd28f29555c/server/etcdserver/apply.go#L147-L160
> etcd: help fuzzer progress

- projects/argo/build.sh
- projects/argo/project_fuzzer.go
Adds a fuzzer for `project.CreateToken`.
> argo: add CreateToken fuzzer

- projects/argo/build.sh
- projects/argo/operator_fuzzer.go
- projects/argo/seeds/workflow_server_fuzzer/seed1
- projects/argo/seeds/workflow_server_fuzzer/seed2
- projects/argo/seeds/workflow_server_fuzzer/seed3
- projects/argo/seeds/workflow_server_fuzzer/seed4
- projects/argo/seeds/workflow_server_fuzzer/seed5
- projects/argo/workflow_server_fuzzer.go
- projects/argo/workflow_v1alpha1_fuzzers.go
1. Catch false positives in `FuzzOperator`
2. Adds 2 fuzzers: `FuzzWorkflowServer`, `FuzzContainerSetTemplateValidate`
3. Adds seed for `FuzzWorkflowServer`
> argo: Add and modify fuzzers

- projects/vitess/build.sh
- projects/vitess/vt_schema_fuzzer.go
Add the files from https://github.com/vitessio/vitess/pull/9477 to use these with OSS-fuzz temporarily until https://github.com/vitessio/vitess/pull/9477 gets merged.
> vitess: add temporary files

- projects/etcd/build.sh
- projects/etcd/filepurge_fuzzer.go
> etcd: add fuzzer

- projects/containerd/cri_fuzzer2.go
Switches the cri service to be created by `NewCRIService` which is the way it is done in production.
> containerd: use production cri service

- projects/argo/repository_fuzzer.go
Adjusts a fuzzer according to recent upstream changes that broke it.
> argo: Fix broken fuzzer

- projects/argo/operator_fuzzer.go
Should help the fuzzer to not be blocked by https://github.com/kubernetes/client-go/blob/master/dynamic/fake/simple.go#L52
> argo: check if workflow is valid before creating it

- projects/argo/argo-cd_util_grpc_fuzzer.go
- projects/argo/build.sh
Adds fuzzer for `userAgentEnforcer`.
> argo: Add grpc fuzzer

- projects/argo/ancestry_fuzzer.go
Use `testFuzzContext` to avoid returning `nil` in `GetTask`
> argo: refactor FuzzGetTaskDependencies

- projects/etcd/etcdserver_fuzzer.go
Catches more cases in the etcdserver fuzzers.
> etcd: Catch more cases

- projects/etcd/build.sh
- projects/etcd/snapshot_fuzzer.go
Creates more files in the folder with the snap files.
> etcd: create more files in snapshot fuzzer

- projects/cluster-api/build.sh
- projects/cluster-api/conversion_fuzzer.go
1. Refactor fuzzer to avoid false positives like https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44857&q=cluster-api&can=1.
2. Add more types to be tested.
> cluster-api: Fix v1alpha3 fuzzer

- projects/cri-o/build.sh
- projects/cri-o/fuzz_server.go
Adds the CRI-O project with its first fuzzer.
> Add cri-o project

- projects/cri-o/build.sh
- projects/cri-o/dicts/fuzz_server.dict
- projects/cri-o/fuzz_server.go
Adds logSanitizer for the server fuzzer.
Also adds some additional logic for the `ListPodSandbox()` call.
> cri-o: Add LogSAN

- projects/cri-o/build.sh
- projects/cri-o/container_server_fuzzer.go
This runs and gets 70%+ coverage of container_server.go, but, it needs
to be improved.
> cri-o: add container server fuzzer

- projects/cri-o/fuzz_server.go
- Adds logs that can be activated in the case of debugging.
- Fixes a blocker.
- Shows the RPC call in the switch statement as a string instead of an int.
> cri-o: Refactor server fuzzer

- projects/cri-o/fuzz_server.go
1. Randomly create containers
2. Clean up sandboxes and containers
3. Randomize paths of logfiles for sandboxes in case multiple are created.
> cri-o: Improve server fuzzer

- projects/kubeedge/build.sh
- projects/kubeedge/lane_fuzzer.go
KubeEdge is being integrated in OSS-Fuzz here: https://github.com/google/oss-fuzz/pull/7755.
We should start using the CNCF-Fuzzing integration after its initial integration into OSS-Fuzz.
> KubeEdge: Initial integration

- projects/cluster-api/build.sh
- projects/cluster-api/topology_cluster_reconciler_fuzzer.go
> cluster-api: Fix broken build

- projects/crossplane/build.sh
- projects/crossplane/composite_fuzzer.go
- projects/crossplane/composition_fuzzer.go
- projects/crossplane/manager_fuzzer.go
Adds the Crossplane project with a few fuzzers
> Add Crossplane project

- projects/vitess/parser_fuzzer.go
- projects/vitess/tabletserver_fuzzer.go
- projects/vitess/tabletserver_schema_fuzzer.go
- projects/vitess/vstreamer_fuzzer.go
- projects/vitess/vt_schema_fuzzer.go
- projects/vitess/vtgate_engine_fuzzer.go
- projects/vitess/vttablet_fuzzer.go
> vitess: recover in multiple fuzzers

- projects/cilium/OnData_fuzzer.go
- projects/cilium/bpf_fuzzer.go
- projects/cilium/build.sh
- projects/cilium/elf_fuzzer.go
- projects/cilium/hubble_parser_fuzzer.go
- projects/cilium/labels_fuzzer.go
- projects/cilium/matchpattern_fuzzer.go
> cilium: add fuzzers

- projects/crossplane/build.sh
- projects/crossplane/xpkg_fuzzer.go
> crossplane: Move fuzzer over from oss-fuzz

- projects/crossplane/build.sh
- projects/crossplane/revision_fuzzer.go
> crossplane: Add two fuzzers

- projects/cilium/build.sh
- projects/cilium/payload_fuzzer.go
> cilium: Add payload fuzzer

- projects/cilium/build.sh
- projects/cilium/format_fuzzer.go
- projects/cilium/monitor_fuzzer.go
> cilium: add two fuzzers

- projects/cluster-api/patch_fuzzer.go
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>
Fix a build error introduced by a change in the underlying Cluster API codebase in PR https://github.com/kubernetes-sigs/cluster-api/pull/6401
> Fix Cluster API Patch signature

- projects/crossplane/build.sh
- projects/crossplane/patch_fuzzer.go
> crossplane: add fuzzer

- projects/cilium/build.sh
- projects/cilium/labelsfilter_fuzzer.go
> Cilium: Add fuzzer

- projects/openyurt/build.sh
Signed-off-by: huiwq1990 <huiwq1990@163.com>
> openyurt: Add fuzzer

- projects/cilium/build.sh
- projects/cilium/fuzz_config_parse.options
> cilium: add options file

- projects/etcd/build.sh
> etcd: fix build

- projects/vitess/vindexes_fuzzer.go
- projects/vitess/vtgate_engine_fuzzer.go
- projects/vitess/vttablet_fuzzer.go
> vitess: fix build

- projects/containerd/build.sh
- projects/containerd/containerd_import_structured_fuzzer.go
> containerd: fix build

- projects/argo/build.sh
- projects/argo/project_fuzzer.go
> argo: fix build

- projects/kubernetes/build.sh
> kubernetes: fix broken build

- projects/helm/build.sh
> helm: fix broken build

- projects/argo/build.sh
> argo: fix broken build

- projects/cilium/format_fuzzer.go
- projects/cilium/hubble_parser_fuzzer.go
- projects/cilium/labelsfilter_fuzzer.go
Format ciliums fuzzers with `goimports`
> cilium: goimports

- projects/kubernetes/build.sh
> Kubernetes: Do not build api_marshalling fuzzer in coverage mode

- projects/helm/fs_fuzzer.go
> helm: fix arbitrary file overwrite in fuzz target

- projects/helm/build.sh
> helm: fix build to account for OSS-Fuzz infra changes

- projects/argo/build.sh
> argo: fix and clean build

- projects/argo/build.sh
- projects/argo/eventbus_controller_fuzzer.go
> argo: fix broken coverage build

- projects/crossplane/build.sh
- projects/crossplane/manager_fuzzer.go
- projects/crossplane/patch_fuzzer.go
- projects/crossplane/revision_fuzzer.go
- projects/crossplane/xpkg_fuzzer.go
> crossplane: fix broken build

- projects/helm/build.sh
> helm: switch dev to master of tooling

- projects/knative/build.sh
- projects/knative/fuzz_activatornet.go
- projects/knative/fuzz_pkg_metrics.go
- projects/knative/fuzz_pkg_websocket.go
- projects/knative/json_fuzzer.go
> add knative fuzzers

- projects/knative/build.sh
- projects/knative/fuzz_pkg_kmeta.go
- projects/knative/fuzz_serving_route_reconciler.go
> knative: add fuzzers

- projects/knative/build.sh
- projects/knative/fuzz_configmaps.go
> knative: add fuzzer

- projects/kubernetes/build.sh
> kubernetes: add more sanitizers

- projects/notary/build.sh
- projects/notary/fuzz_handlers.go
> notary: initial integration

- projects/notary/build.sh
- projects/notary/fuzz_verification.go
> notary: add fuzzer

- projects/etcd/autogenerate_api_marshal_fuzzer.go
- projects/etcd/build.sh
- projects/etcd/etcdserver_fuzzer.go
- projects/etcd/raft_fuzzer.go
- projects/etcd/wal_fuzzer.go
`raft` has been removed from etcd. See:
https://github.com/etcd-io/etcd/commit/56ca9efc57faace05c08875d4f1b25c4bb5b2302
> Fix etcd build

- projects/vitess/abstract_fuzzer.go
- projects/vitess/ast_fuzzer.go
- projects/vitess/tablet_manager_fuzzer.go
- projects/vitess/tabletserver_fuzzer.go
- projects/vitess/tabletserver_schema_fuzzer.go
- projects/vitess/vtctl_fuzzer.go
- projects/vitess/vttablet_fuzzer.go
Further fuzzers in vitess could not be built. This PR fixes all build issues in vitess. Verified that the project can be built now in OSS-Fuzz.
> Fix vitess 

- projects/runc/devices_fuzzer.go
EmulatorFromList is renamed to emulatorFromList
Signed-off-by: Khaled Yakdan <yakdan@code-intelligence.com>
> runc: fix build

- README.md
Signed-off-by: DavidKorczynski <david@adalogics.com>
> README: update list of videos with CNCF fuzzing

- projects/cilium/build.sh
> cilium: build more upstream fuzzers

- projects/notary/build.sh
- projects/notary/fuzz_handlers.go
- projects/notary/fuzz_trustmanager_test.go
> notary: Move fuzzers over from OSS-Fuzz

- projects/knative/build.sh
Same procedure as https://github.com/cncf/cncf-fuzzing/pull/274 now for knative.
> knative: add fork of go-fuzz-headers

- projects/knative/build.sh
- projects/knative/fuzz_sources_v1_experimental.go
Adds another roundtrip fuzzer for knative.
> knative: add roundtrip fuzzer

- projects/vitess/mysql_fuzzer.go
The interface were updated in:
https://github.com/vitessio/vitess/commit/a9a5c7b61818a7d19ac3564f3f2dfe52629e3020
Signed-off-by: Khaled Yakdan <yakdan@code-intelligence.com>
> vitess: add missing functions from the Handler interface

- projects/knative/build.sh
- projects/knative/fuzz_pkg_websocket.go
> knative: add websocket fuzzers

- projects/knative/json_fuzzer.go
> knative: modify webhook json fuzzer

- projects/knative/build.sh
- projects/knative/fuzz_eventing_filter.go
> knative: add filters fuzzer

- projects/notary/fuzz_verification.go
Helps the fuzzer get past the validation of the policyDocument.
> notary: refactor verification fuzzer

- projects/notary/fuzz_verification.go
Improves the verify fuzzer to quicker get past validation.
> notary: improve verification fuzzer

- projects/notary/fuzz_handlers.go
> notary: add error condition in fuzzer

- projects/knative/build.sh
- projects/knative/fuzz_knative_flows_v1.go
> knative: add flows v1 roundtrip fuzzer

- projects/knative/build.sh
- projects/knative/fuzz_knative_eventing_v1.go
> knative: add eventing v1 roundtrip fuzzer

- projects/knative/build.sh
- projects/knative/fuzz_knative_duck_v1beta1.go
> knative: add duck v1beta1 roundtrip fuzzer

- projects/knative/build.sh
- projects/knative/fuzz_knative_duck_v1.go
> knative: add pkg duck v1 roundtrip fuzzer

- projects/knative/fuzz_activatornet.go
> knative: improve throttler fuzzer

- projects/knative/fuzz_validation.go
> knative: add more targets to validation fuzzer

- projects/crossplane/composition_fuzzer.go
> crossplane: fix broken fuzzer

- projects/dapr/build.sh
- projects/dapr/fuzz_expr_test.go
> dapr: add first fuzzer

- projects/knative/fuzz_knative_duck_v1.go
- projects/knative/fuzz_knative_duck_v1beta1.go
- projects/knative/fuzz_knative_eventing_v1.go
- projects/knative/fuzz_knative_flows_v1.go
- projects/knative/fuzz_knative_pkg_serving_v1.go
- projects/knative/fuzz_sources_v1_experimental.go
> knative: generate custom types with funcs

- projects/dapr/build.sh
- projects/dapr/fuzz_messaging_test.go
Adds fuzzer for `pkg/messaging`
> dapr: add fuzzer

- projects/dapr/build.sh
- projects/dapr/fuzz_actors_test.go
Adds the initial fuzzer for the actors package.
> dapr: add actors fuzzer

- projects/dapr/fuzz_messaging_test.go
Remove grpc server and use fakes instead.
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56029
> dapr: remove grpc server in fuzzer

- projects/kubernetes/build.sh
- projects/kubernetes/deployment_util_fuzzer.go
- projects/kubernetes/internal_kubelet_fuzzer.go
- projects/kubernetes/internal_kubelet_kuberuntime_fuzzer.go
1. Modify some calls to APIs that have changed upstream.
2. Remove some `git clone`s and `wget`s to add them in the `Dockerfile` instead.
> kubernetes: fix build

- projects/notary/fuzz_verification.go
Use non-skipVerifier and remove helper code that is no longer needed.
> notary: verification fuzzer - don't use skip verifier

- projects/vitess/autogenerate/convert_grep_to_fuzzer.go
- projects/vitess/build.sh
- projects/vitess/fuzz_keyspace_creation.go
- projects/vitess/fuzz_shard_creation.go
> vitess: add 2 fuzzers

- projects/dapr/fuzz_aescbcaead_test.go
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58727 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58763
> dapr: fix false positives

- projects/dapr/fuzz_aescbcaead_test.go
1. Change where parameters are created.
2. Add `nil` check for `aead`
> dapr: refactor aescbcaead fuzzer

- projects/dapr/fuzz_kit_crypto_test.go
> dapr: do more checks in crypto keys fuzzer

- projects/dapr/fuzz_aescbcaead_test.go
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58866
Also runs `gofmt`
> dapr: Fix OSS-Fuzz issue

- projects/dapr/build.sh
- projects/dapr/fuzz_aescbcaead_test.go
- projects/dapr/pkcs7_padding.go
Attempt to fix:
- https://oss-fuzz.com/testcase-detail/6581492541947904
- https://oss-fuzz.com/testcase-detail/6563724027363328
> dapr: attempt to fix libFuzzer const overwrite

- projects/distribution/app_fuzzer.go
fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59648
> distribution: fix broken fuzzer

- projects/dapr/fuzz_http_endpoints_test.go
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60143
> dapr: fix false positive

- projects/dapr/build.sh
- projects/dapr/fuzz_sidecar_test.go
> dapr: bump dependency with fix for fuzzing issue

- projects/vitess/build.sh
Allows the fuzzers to use them.
> vitess: move test files

- projects/cilium/build.sh
And clean the build file a bit.
> cilium: use Go 1.20

- projects/keycloak/JwkParserFuzzer.java
- projects/keycloak/SamlParserFuzzer.java
- projects/keycloak/build.sh
This PR adds the base fuzzers for project keycloak.
> keycloak: add base fuzzer

- projects/keycloak/build.sh
Fix a relative path error in the project keycloak build.sh
> Fix build script for keycloak

- projects/keycloak/build.sh
> keycloak: Fix wrong java path

- projects/keycloak/build.sh
This PR fixes the wrong revert of permission in #391.
> Keycloak: Fix wrong revert of permission

- projects/keycloak/JwkParserFuzzer.java
- projects/keycloak/SamlParserFuzzer.java
- projects/keycloak/build.sh
This PR fixes the license and jar discovery logic for keycloak
> Fix license and jar discovery logic

- projects/keycloak/build.sh
Fix typo in build.sh for key cloak
> Keycloak: Fix bug

- projects/keycloak/JoseParserFuzzer.java
- projects/keycloak/JsonSerializerDeserializationFuzzer.java
> Keycloak: Add new fuzzers for keycloak

- projects/keycloak/JweFuzzer.java
- projects/keycloak/KeyPairVerifierFuzzer.java
Adding 2 new fuzzers for keycloak.
> Keycloak: New fuzzer

- projects/keycloak/JoseParserFuzzer.java
- projects/keycloak/JsonSerializerDeserializationFuzzer.java
- projects/keycloak/JweFuzzer.java
- projects/keycloak/JwkParserFuzzer.java
- projects/keycloak/KeyPairVerifierFuzzer.java
- projects/keycloak/SamlParserFuzzer.java
Add comments and description to keycloak fuzzers.
> Keycloak: Add detail comments to the fuzzer

- projects/keycloak/build.sh
Fix build script for missing jar dependencies.
> Keycloak: Fix build script

- projects/keycloak/TokenVerifierFuzzer.java
Add new fuzzer for project keycloak
> Keycloak: Add TokenVerifierFuzzer

- projects/keycloak/JwksUtilsFuzzer.java
Add new fuzzer for keycloak targeting JWKSUtils and JWKBuilder class.
> Keycloak: Add new fuzzer for keycloak

- projects/keycloak/TokenUtilFuzzer.java
Add fuzzer to target TokenUtil class of keycloak.
> Keycloak: Create TokenUtilFuzzer for keycloak

- projects/keycloak/TokenUtilFuzzer.java
Fix fuzzer comment for keycloak TokenUtilFuzzer.
> Keycloak: Fix fuzzer comment

- projects/keycloak/CommonUtilsFuzzer.java
This fuzzer targets utils method in different Utils class in the keycloak common package.
> keycloak:Create CommonUtilsFuzzer

- projects/keycloak/CommonCryptoUtilsFuzzer.java
This fuzzer targets utils methods in different Crypto related Utils class in the keycloak common package.
> keycloak: Create new fuzzer for keycloak

- projects/keycloak/CommonCryptoUtilsFuzzer.java
This PR fixes the fuzzer formatting and the copy bug of method call.
> keycloak: Fix copy bug

- projects/keycloak/CommonUtilsFuzzer.java
- projects/keycloak/JsonSerializerDeserializationFuzzer.java
- projects/keycloak/JweFuzzer.java
- projects/keycloak/JwksUtilsFuzzer.java
- projects/keycloak/SamlParserFuzzer.java
- projects/keycloak/TokenUtilFuzzer.java
- projects/keycloak/TokenVerifierFuzzer.java
Fix formatting of keycloak fuzzers.
> Keycloak: Fix fuzzer format

- projects/keycloak/build.sh
This PR fixes the build.sh to exclude some modules and also activate the shade plugin my slighly in build modification of the pom.xml.
> Keycloak: Fix build script and maven shading

- projects/keycloak/PolicyEnforcerFuzzer.java
- projects/keycloak/build.sh
Creating fuzzer for policy enforcer.
> Keycloak: Policy enforcer fuzzer

- projects/keycloak/PolicyEnforcerFuzzer.java
Fix randoming data using logic and comments of policyenforcerfuzzer.
> keycloak: Fix fuzzer logic and comments

- projects/kyverno/fuzz_engine_test.go
Structures how the fuzzer creates the policy and the unstructured object. This makes the fuzzer a lot more effective in reaching the handler invocation.
> kyverno: optimize validation fuzzer

- projects/keycloak/JweAlgorithmProviderFuzzer.java
> keycloak: Fix switch statement

- projects/keycloak/JweAlgorithmProviderFuzzer.java
> keycloak: Improve comments

- projects/keycloak/ServicesUtilsFuzzer.java
- projects/keycloak/build.sh
Add fuzzer for the service/utils package
> Keycloak: Add ServicesUtilsFuzzer

- projects/keycloak/ServicesJwsFuzzer.java
- projects/keycloak/build.sh
Create fuzzer for services/jws package.
> Keycloak: Create fuzzer for services jws package

- projects/keycloak/AuthorizationTokenServiceFuzzer.java
- projects/keycloak/build.sh
Fix build script and create fuzzer for the services/authorization package.
> Keycloak: Create AuthorizationTokenServiceFuzzer

- projects/keycloak/ServicesValidationFuzzer.java
Catch some internally wrapped runtime exception.
> keycloak: Catch uri exception

- projects/keycloak/build.sh
Fix build script to exclude dependencies from keycloak jar for fuzz-introspector build.
> keycloak: Fix build script for fuzz-introspector

- projects/keycloak/CryptoProviderfuzzer.java
Create new fuzzer for crypto provider package.
> Keycloak: Cryptoproviderfuzzer

- projects/keycloak/ClientSignatureVerifierProviderFuzzer.java
- projects/keycloak/SignatureProviderFuzzer.java
Add new fuzzers for crypto providers.
> keycloak: Add new fuzzers for crypto provider

- projects/keycloak/CredentialValidatorFuzzer.java
This PR adds a new fuzzer for the CredentialProvider classes.
> Keycloak: Add new fuzzer CredentialProvider

- projects/keycloak/AuthenticatorFuzzer.java
This PR adds a new fuzzer for the authenticator package of project Keycloak.
> Keycloak: add fuzzer for authenticator package

- projects/cubefs/fuzz_datanode.go
The fuzz test case of the disk failed to initialize properly
close:#65561    https://oss-fuzz.com/testcase-detail/6294586066337792
> fix(CubeFS): The fuzz test case of the disk failed to initialize properly

- projects/keycloak/ValidatorFuzzer.java
This PR adds a new fuzzer for the Validators classes in Keycloak.
> Keycloak: Add new fuzzer for validators

- projects/keycloak/TokenUtilFuzzer.java
This PR fixes the existing TokenUtilsFuzzer of the Keycloak project to include more uncovered methods.
> keycloak: Fix TokenUtilsFuzzer

- projects/keycloak/AuthenticationManagerFuzzer.java
This PR adds a new fuzzer for the AuthenticationManager class in Keycloak project.
> Keycloak: Add AuthenticationManagerFuzzer

- projects/keycloak/SamlParserFuzzer.java
This PR fixes the original SamlParserFuzzer to include fuzzing to some other Saml Parser in the project.
> keycloak: Fix SamlParserFuzzer

- projects/keycloak/SamlProtocolParserFuzzer.java
This PR adds a fuzzer targeting the Saml Protocol Parser package.
> Keycloak: Add SamlProtocolParserFuzzer

- projects/keycloak/SamlMetadataParserFuzzer.java
This PR adds a fuzzer targeting parsing method of the saml metadata parser classes..
> Keycloak: Add SamlmetadataParserFuzzer

- projects/keycloak/SamlConfigParserFuzzer.java
This PR add a fuzzer targeting parsing method of Saml Config related parser classes.
> Keycloak: Add SamlConfigParserFuzzer

- projects/keycloak/SamlAssertionParserFuzzer.java
This PR add a fuzzer targeting parsing method of Saml Assertion related parser classes.
> keycloak: Add SamlAssertionParserFuzzer

- projects/keycloak/SamlXmlUtilFuzzer.java
- projects/keycloak/build.sh
This PR adds a new fuzzer for XMLUtil related class for SAML in Keycloak project. Also, the build script is fixed to add seed to fuzzers.
> Keycloak: Add new fuzzer and fix build script

- projects/keycloak/SamlAssertionParserFuzzer.java
- projects/keycloak/SamlConfigParserFuzzer.java
- projects/keycloak/SamlMetadataParserFuzzer.java
- projects/keycloak/SamlParserFuzzer.java
- projects/keycloak/SamlProcessingUtilFuzzer.java
- projects/keycloak/SamlProtocolParserFuzzer.java
- projects/keycloak/SamlValidationUtilFuzzer.java
- projects/keycloak/SamlXmlUtilFuzzer.java
- projects/keycloak/build.sh
This PR adds 2 new fuzzers and fixes the fuzzers for Saml related methods and classes. This PR also fixes the build script.
> Keycloak: Add and fix Saml related fuzzers and build script

- projects/keycloak/BaseKeycloakSessionFuzzer.java
- projects/keycloak/DefaultAuthenticationFlowsFuzzer.java
- projects/keycloak/build.sh
This PR adds new fuzzer and fix build script.
> Keycloak: Add fuzzers and fix build script

- projects/keycloak/BaseHelper.java
This PR fixes the base helper, adding more randomized items to the fuzzers for keycloak project.
> Keycloak: Fix Base helper

- projects/keycloak/BaseHelper.java
- projects/keycloak/build.sh
This PR continues the work on expanding the mocking object of KeycloakSession to allow fuzzing more methods in the Keycloak project. This PR also refines the build script in order to decrease the modules built and possible timeout during building process.
> Keycloak: Fix build and fuzzers

- projects/keycloak/BaseHelper.java
This PR continues to modify the BaseHelper to include more randomised object in Validator and Keycloak Session handling.
> Keycloak: Fix fuzzer for more validating providers

- projects/keycloak/BaseHelper.java
- projects/keycloak/ConditionalAuthenticatorFuzzer.java
- projects/keycloak/ResetcredAuthenticatorFuzzer.java
This PR adds more fuzzers for Authenticator implementing classes.
> Keycloak: Add more fuzzers

- projects/keycloak/BrokerAuthenticatorFuzzer.java
- projects/keycloak/ResetcredAuthenticatorFuzzer.java
- projects/keycloak/X509AuthenticatorFuzzer.java
This PR adds and fixes more fuzzer for keycloak project.
> Keycloak: Add and fix fuzzers

- projects/keycloak/BaseHelper.java
- projects/keycloak/KeycloakModelUtilsFuzzer.java
- projects/keycloak/build.sh
This PR adds more fuzzers for the keycloak project.
> Keycloak: more fuzzers

- projects/keycloak/JweAlgorithmProviderFuzzer.java
The API of the JweAlgorithmProvider interface has been changed in the latest update of Keycloak and cause the fuzzer build fails. This PR fixes the fuzzers to match the new API of the JweAlgorithmProvider.
> Keycloak: Fix fuzzer for API changes

- projects/keycloak/KeycloakModelUtilsFuzzer.java
- projects/keycloak/build.sh
This PR fixes the build for Keycloak project to accommodate a recent API changes in Keycloak that cause the build failing in OSS-Fuzz.
> Keycloak: Fix build

- projects/keycloak/DirectGrantAuthenticatorFuzzer.java
- projects/keycloak/JsonSerializerDeserializerFuzzer.java
- projects/keycloak/JweAlgorithmProviderFuzzer.java
- projects/keycloak/JwkParserFuzzer.java
- projects/keycloak/JwksUtilsFuzzer.java
- projects/keycloak/KeycloakModelUtilsFuzzer.java
- projects/keycloak/KeycloakUriBuilderFuzzer.java
- projects/keycloak/PemUtilsProviderFuzzer.java
- projects/keycloak/ResetcredAuthenticatorFuzzer.java
- projects/keycloak/SamlConfigParserFuzzer.java
- projects/keycloak/SamlMetadataParserFuzzer.java
- projects/keycloak/SamlParserFuzzer.java
- projects/keycloak/SamlProcessingUtilFuzzer.java
- projects/keycloak/SamlProtocolParserFuzzer.java
- projects/keycloak/SamlValidationUtilFuzzer.java
- projects/keycloak/SamlXmlUtilFuzzer.java
- projects/keycloak/ServicesJwsFuzzer.java
- projects/keycloak/ServicesUtilsFuzzer.java
- projects/keycloak/TokenUtilFuzzer.java
- projects/keycloak/ValidatorFuzzer.java
- projects/keycloak/X509AuthenticatorFuzzer.java
Same work as in https://github.com/cncf/cncf-fuzzing/pull/503 for different fuzzers.
> keycloak: refactor fuzzers

- projects/keycloak/CredentialValidatorFuzzer.java
This PR adds exception handling for some underlying exceptions wrapped in general RuntimeException to avoid throwing out expected exceptions.
> Keycloak: Fix exception wrapped

- projects/keycloak/BaseHelper.java
- projects/keycloak/KeycloakModelUtilsFuzzer.java
This PR fixes a bug in BaseHelper and the wrapped exception handling for KeycloakModelUtilsFuzzer.
> Keycloak: Fix wrapped exceptions

- projects/keycloak/AuthzClientFuzzer.java
This PR fixes exception handling for AuthzClientFuzzer.
> Keycloak: Fix exception handling for AuthzClientFuzzer

- projects/keycloak/JweFuzzer.java
- projects/keycloak/JwkParserFuzzer.java
> Keycloak: Fix jwkparserfuzzer

- projects/keycloak/JweAlgorithmProviderFuzzer.java
This PR temporary remove fips classes to avoid crashing.
> Keycloak: Temporary removing fips classes

- projects/keycloak/CertificateUtilsProviderFuzzer.java
> Keycloak: Catch expected error

- projects/keycloak/AuthzClientFuzzer.java
This PR fixes the AuthzClientFuzzer.
> Keycloak: Fix authz client fuzzer

- projects/keycloak/ServicesJwsFuzzer.java
This PR fixes potential problems in the ServicesJwsFuzzer which lead to no coverage increase.
> Keycloak: Fix ServicesJwsFuzzer

- projects/keycloak/BaseHelper.java
- projects/keycloak/build.sh
This PR fixes the build script and BaseFuzzer following the latest changes in the Keycloak repository.
> Keycloak: Fix build script and BaseFuzzer

- projects/cri-o/ParseStoreReference_fuzzer.go
- projects/cri-o/build.sh
- projects/cri-o/config_fuzzer.go
- projects/cri-o/container_fuzzer.go
- projects/cri-o/container_server_fuzzer.go
- projects/cri-o/fuzz_server.go
- projects/cri-o/util/mock_helpers_test.go
This fixes the fuzzers that have broken Go code. The build still has some linker issues.
> cri-o: fix parts of the broken build

- projects/runc/build.sh
> runc: fix broken build

- projects/etcd/etcdserver_fuzzer.go
Ignore crashes like https://oss-fuzz.com/testcase-detail/5623247088975872
> etcd: fix false positive

- projects/vitess/build.sh
- projects/vitess/vreplication_fuzzer.go
This currently breaks the build
> vitess: fix panic in multiple fuzzers

- projects/keycloak/CredentialValidatorFuzzer.java
- projects/keycloak/ServicesUtilsFuzzer.java
- projects/keycloak/build.sh
This PR fixes keycloak build to match new upstream API.
> Keycloak: Fix keycloak build new
