cncf/cncf-fuzzing

projects/etcd/build.sh

1. Switches the build of the fuzzers to OSS-fuzz's `compile_go_fuzzer`.
2. Use module paths instead of `.`

etcd: Refactor

---

projects/kubernetes/aes_fuzzer.go
projects/kubernetes/apiextensions_fuzzer.go
projects/kubernetes/apiserver_fuzzer.go
projects/kubernetes/build.sh
projects/kubernetes/converter_fuzzer.go
projects/kubernetes/deepcopy_fuzzer.go
projects/kubernetes/gofuzz-fuzzers.go
projects/kubernetes/internal_kubelet_server_fuzzer.go
projects/kubernetes/kubectl_fuzzer.go
projects/kubernetes/kubelet_fuzzer.go
projects/kubernetes/parser_fuzzer.go
projects/kubernetes/roundtrip_fuzzer.go
projects/kubernetes/validation_fuzzer.go

1. Applies `gofmt` and `goimports`.
2. Removes inline comments
3. Disables the `FuzzRequest` fuzzer as it is not suited yet to run continuously.

kubernetes: Refactor fuzzers

---

projects/etcd/build.sh
projects/etcd/etcdserver_fuzzer.go

Adds a fuzzer for `(s *EtcdServer).apply()` that creates randomized entries and passes them to `(s *EtcdServer).apply()`.
Since this fuzzer runs into some manually added panics, some of the panics are recovered.
An example of such panics is [this one](https://github.com/etcd-io/etcd/blob/29292aa7bdafaf65cb5e054591fe0ff07b36f5ee/pkg/pbutil/pbutil.go#L36-L40):
```go
func MustUnmarshal(um Unmarshaler, data []byte) {
if err := um.Unmarshal(data); err != nil {
panic(fmt.Sprintf("unmarshal should never fail (%v)", err))
}
}
```
As an example, the fuzzer will generate invalid wire types, and recovering allows it to run continuously.

etcd: Add etcdserver fuzzer

---

projects/etcd/build.sh
projects/etcd/raft_fuzzer.go

1. Removes `FuzzNetworkSend`
2. Ensures correct msg type on every iteration.
3. Prevents the fuzzer from crashing from known errors in etcd by recovering manually added panics.

etcd: Refactor raft fuzzers

---

projects/etcd/build.sh
projects/etcd/proxy_fuzzer.go

Adds a fuzzer that sets up a proxy server and passes pseudo-random data to it.
This fuzzer tests the `etcd/pkg/proxy` package.

etcd: Add proxy fuzzer

---

projects/etcd/autogenerate_api_marshal_fuzzer.go
projects/etcd/build.sh

Adds a script that autogenerates a fuzzer for the api marshaling routines.
The fuzzer is more than 4000 lines long and contains lots of repetitive code. For ease of maintenance it is autogenerated via this script.

etcd: Add api marshaling fuzzer

---

projects/kubernetes/kubectl_fuzzer.go

Use `sync.Once` to only init for the kubectl fuzzer.

Kubernetes: Only init in kubectl fuzzer

---

projects/kubernetes/build.sh
projects/kubernetes/deepcopy_fuzzer.go

1. Select a single version and kind instead going through all in each iteration. Will speed up the fuzzer.
2. Change two `panics` to `errors`.
3. Change 2 error messages.

kubernetes: Refactor deep copy fuzzer

---

projects/kubernetes/converter_fuzzer.go

Prints out the diff between the two obects in case of a crash.

kubernetes converter fuzzer: Print failed out failed objects

---

projects/argo/build.sh
projects/argo/normalizer_fuzzer.go
projects/argo/repository_fuzzer.go
projects/argo/sessionmanager_fuzzer.go
projects/argo/workflow_parser_fuzzer.go
projects/argo/workflow_validation_fuzzer.go

Moves the fuzzers at https://github.com/google/oss-fuzz/tree/master/projects/argo over to cncf-fuzzing.
Also adds a few more fuzzers.

argo: Move fuzzers to cncf-fuzzing

---

projects/etcd/build.sh

1. Fail entire build and report if a single fuzzer cannot be built.
2. Remove one of the fuzzers after it has been built.

etcd: minor refactoring

---

projects/etcd/build.sh
projects/etcd/v2_http_kv_fuzzer.go

Adds the `FuzzV2HTTP` fuzzer.
Applies some refactoring:
- Add path when compiling fuzzers in `/tests/fuzzing`
- Change` [ "$SANITIZER" != "coverage" ]` to `if [ "$SANITIZER" = "coverage" ]`

etcd: Add v2_http_kv fuzzer

---

projects/kubernetes/gofuzz-fuzzers.go

Moves the bytesource helpers to go-fuzz-headers. The fuzzers imports them from there instead.

kubernetes: refactor

---

projects/etcd/build.sh
projects/etcd/wal_fuzzer.go

Moves the fuzzer to cncf-fuzzing from https://github.com/google/oss-fuzz/blob/master/projects/etcd/wal_fuzzer.go

etcd: move wal fuzzer over from oss-fuzz

---

projects/etcd/build.sh

The fuzzer times out very quickly. This fixes the issue locally.

etcd: experimental fix for api marshal fuzzer

---

projects/distribution/authchallenge_fuzzer.go
projects/distribution/build.sh
projects/distribution/client_fuzzer.go
projects/distribution/inmemory_fuzzer.go
projects/distribution/storage_fuzzer.go
projects/distribution/token_fuzzer.go

1. Delete fuzzers here that are merged upstream
2. Build upstream fuzzers
3. Add more fuzzers
4. Reduce `noOfExecs` in inmemory fuzzer
5. Do so that if any fuzzer fails to be built, it gets reported in OSS-fuzz.

distribution: Clean up and add more fuzzers

---

projects/etcd/build.sh
projects/etcd/cluster_utils.go
projects/etcd/grpc_proxy_fuzzer.go
projects/etcd/v3_grpc_fuzzer.go

`cluster_utils.go`:
- Adds a rewritten version of the test helpers to create clusters that are more friendly for fuzzing.
`FuzzKVProxy`:
- Use the new test helpers.
- Create requests before creating a cluster.
- Make requests after cluster has been set up.
- Create a cluster every iteration - after having created the requests - instead of every 50 000 iterations.
- Add clean up to remove cluster pipe
`FuzzGRPCApis`:
- Use the new test helpers.
- Add clean up to remove cluster pipe

etcd: refactor 2 fuzzers

---

projects/argo/project_fuzzer.go

Please merge only after https://github.com/argoproj/argo-cd/pull/8136 has been merged.
Referenced PR switches jwt-go library in Argo CD that fixes https://oss-fuzz.com/testcase-detail/5460437754314752
Signed-off-by: jannfis <jann@mistrust.net>

[Argo]: Change import in fuzzer due to upstream change

---

projects/etcd/etcdserver_fuzzer.go

Improves the etcdserver significantly by setting the Op specifically and only setting a single Op, which is required in https://github.com/etcd-io/etcd/blob/main/server/etcdserver/apply.go#L135. The fuzzer gets stuck here: https://github.com/etcd-io/etcd/blob/f75549d53b93f44ff43dbd4c9279612c974edcd3/server/etcdserver/apply.go#L148-L160, but with the changes in this PR, it makes it past that section instantly.

etcd: improve etcdserver fuzzer

---

projects/etcd/v3_grpc_fuzzer.go

cleans up the created files at runtime.

etcd: clean up grpc apis fuzzer

---

projects/argo/artifacts_fuzzer.go

A panic in a helper function broke these two fuzzers. This PR allows the fuzzers to instead exit gracefully.

argo: Avoid panic in helper function

---

projects/cluster-api/build.sh
projects/cluster-api/conversion_fuzzer.go

Adds a fuzzer for the logic implemented in `https://github.com/kubernetes-sigs/cluster-api/blob/main/util/conversion.FuzzTestFunc`.

cluster-api: Add roundtrip fuzzer

---

projects/cluster-api/bootstrap_kubeadm_fuzzer.go
projects/cluster-api/cluster_controller_fuzzer.go
projects/cluster-api/crd-creation/main.go
projects/cluster-api/non-oss-fuzz/Dockerfile
projects/cluster-api/non-oss-fuzz/build.sh
projects/cluster-api/non-oss-fuzz/run_fuzzer.sh

Adds a reconciler fuzzer that makes use of envtest. This is not supported by OSS-fuzz, so a separate Dockerfile is added to run the fuzzer locally.

cluster-api: Add reconciler fuzzer

---

projects/cluster-api/build.sh
projects/cluster-api/topology_cluster_reconciler_fuzzer.go

1. Replace contexts with `context.Background()`
2. Add `Blueprint` validation
3. Add a fuzzer for the exported `Reconcile()` and deactivate the 3 fuzzers for the non-exported APIs. This is experiemental.

cluster-api: Small fixes to fuzzers

---

projects/cri-o/build.sh

All dependencies are installed in the Dockerfile

cri-o: Do not install dependencies in build script

---

projects/kubernetes/api_roundtrip_fuzzer.go
projects/kubernetes/build.sh
projects/kubernetes/roundtrip.go

- Adjusts the build to Kubernetes recently having upgraded to Go 1.18.
- Adds API roundtrip fuzzer.
- Adds a modified version of the roundtrip test.

Kubernetes: Refactor build and add api roundtrip fuzzer

---

projects/vitess/vtctl_fuzzer.go

In `cncf-fuzzing/projects/vitess/vtctl_fuzzer.go`, the function `getCommandType` contains 69 cases ([0, 68]). However, the fuzzer always miss the case 68 since it mods to 68. I fixed it to 69.
Signed-off-by: happy-qop <all.u.ever.know@gmail.com>

fix missing case (68 -> 69), fix sign-off issue

---

projects/vitess/parser_fuzzer.go
projects/vitess/planbuilder_fuzzer.go
projects/vitess/tabletserver_schema_fuzzer.go
projects/vitess/vstreamer_fuzzer.go
projects/vitess/vt_schema_fuzzer.go
projects/vitess/vtgate_engine_fuzzer.go
projects/vitess/vttablet_fuzzer.go

Made a small mistake in https://github.com/cncf/cncf-fuzzing/pull/197. The recover statements should be deferred.

vitess: defer recoveries

---

projects/cilium/OnData_fuzzer.go
projects/cilium/build.sh

The Cilium coverage build is failing because the corpus for the `fuzz_parsers` fuzzer cannot be found. This PR renames it in an attempt to fix the issue.

Cilium: Attempt to fix broken coverage build

---

projects/cluster-api/conditions_fuzzer.go
projects/cluster-api/patch_fuzzer.go

Signed-off-by: killianmuldoon <kmuldoon@vmware.com>
Fix assignment errors - one of them introduced by my previous PR in #205 - to allow Cluster API fuzzers to build.

Cluster API: Fix assignment build errors for fuzzers

---

projects/kubeedge/build.sh
projects/kubeedge/cloudhub_messagehandler_fuzzer.go

Signed-off-by: wackxu <xushiwei5@huawei.com>
We are refactoring the kubeedge cloudhub module in https://github.com/kubeedge/kubeedge/pull/4176 and moving the VolumeRegExp to the common package, so we need to change FuzzVolumeRegExp

fix kubeedge FuzzVolumeRegExp

---

projects/distribution/reference_fuzzer2.go

- relates to https://github.com/distribution/distribution/pull/3774
The "shortid" format, as implemented in the ParseAnyReferenceWithSet() function has been deprecated, and will be removed from the distribution repository.

distribution: remove fuzzing for deprecated reference formats

---

projects/cilium/bpf_fuzzer.go
projects/cilium/build.sh

The fuzzer was removed here as a quick fix for the broken build: https://github.com/cncf/cncf-fuzzing/pull/228. This PR brings it back.

cilium: bring back bpf fuzzer

---

projects/knative/build.sh
projects/knative/fuzz_messaging_v1.go

Adds a roundtrip fuzzer using the existing fuzzer functions.
Adds some logic from the k8s roundtrip tests which I will break out later to a separate module.

knative: add roundtrip fuzzer

---

projects/argo/repository_fuzzer.go

`GenerateManifests` takes a 9th mandatory parameter `gitRepoPaths io.TempPaths`.

Fix argo's repository fuzzer

---

projects/vitess/abstract_fuzzer.go
projects/vitess/build.sh
projects/vitess/mysql_fuzzer.go

`abstract/fuzz.go` has been moved to `operators/fuzz.go`

vitess: fix build

---

projects/distribution/build.sh
projects/distribution/registry_proxy_fuzzer.go
projects/distribution/storage_fuzzer.go

This PR removes deleted scripts and adjusts calls to `memory.NewInMemoryBlobDescriptorCacheProvider`, which now expects an integer argument.

Fix distribution

---

projects/etcd/build.sh
projects/etcd/raft_api_fuzzer.go

This fixes an import in etcd fuzzers and the raft fuzzer. When this PR is merged, the corresponding PR in OSS-Fuzz (https://github.com/google/oss-fuzz/pull/9374) should be also merged.

etcd: fix raft import and fuzzer

---

projects/notary/build.sh

My fork currently has some fixes that won't be merged just yet. Switching to the fork temporarily.

notary: use fork of go-fuzz-headers

---

projects/notary/build.sh
projects/notary/fuzz_tuf_utils.go

Adds a fuzzer for `ParsePEMPrivateKey`.

notary: add fuzzer

---

projects/knative/build.sh
projects/knative/fuzz_messaging_v1_experimental.go
projects/knative/fuzzer_funcs.go

Adds a roundtrip test based on go-fuzz-headers. Also adds a file with upstream k8s functions for the types used in the knative fuzzer.

knative: add experimental roundtrip fuzzer based on go-fuzz-headers

---

projects/knative/fuzz_pkg_websocket.go

Allows the fuzzer to run for longer before hitting https://oss-fuzz.com/testcase-detail/5288967094534144

knative: manually invoke GC in fuzzer

---

projects/dapr/build.sh

dapr: modify build script

---

projects/notary/build.sh
projects/notary/fuzz_verification.go

1. Use goroutines in loops.
2. Don't run regexes.
3. Add defaults if fuzzer cannot generate values.
4. Remove skip verify option.
5. Parse artifact ref early in the fuzzer.

notary: make verification fuzzer faster

---

projects/distribution/reference_fuzzer2.go

Check the error-return value of reference.ParseDockerRef so the fuzz test stops blindly calling reference.TagNameOnly with a nil argument.

distribution: fix spurious fuzz failures

---

projects/argo/build.sh

Which is required to use Go 1.20 and above.
Also bump Go version.

argo: add -lresolv to build env var

---

projects/keycloak/AuthzClientFuzzer.java

This PR creates the fuzzer for AuthzClient class and target its different version of protection and authorization method which depends on a auth web server. Currently, same as #423, it is pointed to empty auth url  to avoid HTTP connection. The next improvement step is to implement mock server service to simulate a response for fuzing those response handling logic. The settings of the auth url is set in a json configuration.

keycloak: Authz client fuzzer

---

projects/keycloak/AuthzClientFuzzer.java
projects/keycloak/PolicyEnforcerFuzzer.java
projects/keycloak/build.sh

Some fuzzer class requires HTTP connection to get response and further process on those response. For example the fuzzers in #423 and #425. In order to accommodate this setting, this PR add the okhttp3.MockWebServer service and related dependencies to allow these fuzzers to create a MockWebServer for random response. The fuzzer points the http auth url to the MockWebServer initialise during fuzzer initialisation process and generate random mock response to trigger those response processing logic for fuzzing. By default, HTTP connection are banned by Jazzer BugDetectors. Specific exclusion predicate can be set to allow HTTP connection to specific hostname and port. This is done in the fuzzerInitialize of the fuzzers to ensure only connection to the localhost mock web server is allowed.

Keycloak: Add mock web server service and relative dependencies

---

projects/keycloak/build.sh

Move the JDK installation logic to oss-fuzz Dockerfile in https://github.com/google/oss-fuzz/pull/10809 to avoid missing native binary from headless version.

keycloak: Move JDK 17 installation to Dockerfile

---

projects/keycloak/ServicesUtilsFuzzer.java

Totputils method capture the underlying exceptions and throw a Runtime Exception. This PR fixes the exception handling to capture the thrown Runtime Exception and check if it is an expected cause, otherwise, the original RuntimeException are thrown out. This could solve some of the problem by handled and expected exceptions.

keycloak:  Fix internal exception

---

projects/keycloak/build.sh

After the changes in #440. The JDK-17 is now installed by apt command in the Dockerfile. The JAVA_HOME and PATH will automatically set by the apt command and thus the manual config of this two environment variable is not needed anymore.

keycloak: Fix java home

---

projects/keycloak/AuthorizationTokenServiceFuzzer.java
projects/keycloak/JsonSerializerDeserializationFuzzer.java
projects/keycloak/PolicyEnforcerFuzzer.java
projects/keycloak/ServicesJwsFuzzer.java
projects/keycloak/ServicesValidationFuzzer.java

It is discovered that some fuzzer runs into OutOfMemoryError because of GC overhead limit exceeded. JDK garbage collection (GC) will try to free up memory when some unused object is found. If there is too much repeating instance creation and dropped, the GC will take up high working load. When the working load is higher than the preset overhead of the JVM (normally set to 98%), an OutOfMemoryError is thrown. Some of the fuzzers of keycloak create a new set of mock object in every iteration. It means that it will build up a high amount of "garbage" for the GC to work with. This eventually reach the GC overhead limit. This PR fixes one of the fuzzer to try moving the mock object creation in the fuzzerInitialize method (which only execute once when the fuzzer start and will not execute per …

keycloak: Move object mocking location

---

projects/keycloak/JweAlgorithmProviderFuzzer.java

Some methods of keycloak wrap internal exceptions with the general Exception. This make it hard to handle separate exceptions from keycloak. This PR modifies the exception handling of JweAlgorithmProviderFuzzer by replacing the capturing of general Exception. The new approach capture certain known exception and throw the other exception out. This could be more precise in finding unexpected exceptions.

Fix general exception handling

---

projects/keycloak/build.sh

Add jdk 17 installation to run script and fix wrong removal of JAVA_HOME and PATH in #441.

keycloak: Fix build script

---

projects/keycloak/AuthorizationTokenServiceFuzzer.java
projects/keycloak/JweAlgorithmProviderFuzzer.java
projects/keycloak/ServicesJwsFuzzer.java
projects/keycloak/ServicesValidationFuzzer.java
projects/keycloak/build.sh

Trial fix of gc overheaed from solution of inline mock memory leak in Mockito mentioned in https://github.com/mockito/mockito/issues/1532

Keycloak: Fix possible mockito gc overhead

---

projects/runc/build.sh

The following error would occur when building fuzz driver `FuzzStateApi` for runc after migrating go version to 1.21.0, which would lead to building failure.
```bash
Running go-fuzz -tags gofuzz -func FuzzStateApi -o state_api_fuzzer.a github.com/opencontainers/runc/libcontainer
libcontainer/dmz/dmz_linux.go:21:12: pattern runc-dmz: no matching files found
failed to build packages:exit status 1
ERROR:__main__:Building fuzzers failed.
```
AFAIU, the reason is runc requires `runc-dmz` binary available for building in [libcontainer/dmz/dmz_linux.go](https://github.com/opencontainers/runc/blob/c494c475bdf7d2fd3b44c79c9c1df7b234ed69dc/libcontainer/dmz/dmz_linux.go#L20C1-L21C20), while go build process would ignore `go:generate` when the target file is not directly used.
Although it would not …

Fix missing runc-dmz failure for runc

---

projects/keycloak/ServicesUtilsFuzzer.java

In https://github.com/keycloak/keycloak/pull/22700, the `GroupUtils.toGroupHierarchy()` method has been removed and new method `GroupUtils.populateGroupHierarchyFromSubGroups()` has been added. This PR changes the ServiceUtilsFuzzer to accommodate this change to fuzz the new method. This PR also fix the formatting of ServiceUtilsFuzzer.

Keycloak: Fix fuzzer for removed API call

---

projects/keycloak/build.sh

Some map related modules are removed in https://github.com/keycloak/keycloak/pull/24541, this PR removes them from the excluded module list to avoid build error.
Also, additional dependencies has been added to the themes module in https://github.com/keycloak/keycloak/pull/24682, this PR fixes the build script to accommodate the changes.

Keycloak: Fix build script for keycloak project

---

projects/distribution/build.sh

[distribution/distribution](https://github.com/distribution/distribution) project no longer supports Go versions < 1.20. 
Deprecating support for the old version of Go runtimes started causing the following fuzzing failures:
```
"go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20"
```
This PR bumps the Go version to the oldest supported version by the distribution project.

Bump go version in distribution project.

---

projects/keycloak/BaseFuzzer.java
projects/keycloak/DirectGrantAuthenticatorFuzzer.java

This PR extends the BaseFuzzer to provide more object implementation and randomization. This allows adding more fuzzing target from more Authenticator class implementations.

Keycloak: Add fuzzers for more Authenticator implementations

---

projects/kubeedge/build.sh

This PR makes KubeEdge's build.sh script to support go work. Kubeedge is being reinvented to support go work https://github.com/kubeedge/kubeedge/pull/5774. An error occurred while running CIFuzz, as follows:
```text
'go mod vendor' cannot be run in workspace mode. Run 'go work vendor' to vendor the workspace or set 'GOWORK=off' to exit workspace mode.
```

KubeEdge: fix build

---

projects/keycloak/AuthenticatorFuzzer.java
projects/keycloak/BrokerAuthenticatorFuzzer.java
projects/keycloak/CertificateUtilsProviderFuzzer.java
projects/keycloak/ClientSignatureVerifierProviderFuzzer.java
projects/keycloak/CommonCryptoUtilsFuzzer.java
projects/keycloak/CommonUtilsFuzzer.java
projects/keycloak/ConditionalAuthenticatorFuzzer.java
projects/keycloak/DefaultAuthenticationFlowsFuzzer.java

In general: Remove `break` at the end of a case in `switch` statements. 
Remove `null` checks before testing the target method: We want to know if this does not work and not hide it.
Rewrite some bytes and strings in the cryptoutils fuzzer to be more flexible.
cc @arthurscchan for info

keycloak: Refactor fuzzers

---

projects/keycloak/AuthenticatorFuzzer.java
projects/keycloak/AuthzClientFuzzer.java
projects/keycloak/BaseHelper.java
projects/keycloak/BrokerAuthenticatorFuzzer.java
projects/keycloak/ConditionalAuthenticatorFuzzer.java
projects/keycloak/DefaultAuthenticationFlowsFuzzer.java
projects/keycloak/DirectGrantAuthenticatorFuzzer.java
projects/keycloak/KeycloakModelUtilsFuzzer.java
projects/keycloak/ResetcredAuthenticatorFuzzer.java
projects/keycloak/ValidatorFuzzer.java
projects/keycloak/X509AuthenticatorFuzzer.java

This PR fixes the logic by cleaning up Mockito objects after use to avoid GC overhead limit exceed when cleaning those objects.

Keycloak: Fix GC overhead limit exceed problem

---

projects/keycloak/ClientSignatureVerifierProviderFuzzer.java

This PR fixes logic in keycloak fuzzers to avoid invalid input cause unexpected NPE.

Keycloak: Fix NPE from invalid input

---

projects/keycloak/JweFuzzer.java

This PR fixes JweFuzzer which the key byte is empty.

Keycloak: Fix empty jwe bug

---

projects/keycloak/KeycloakModelUtilsFuzzer.java

This PR fixes the logic of KeycloakModelUtilsFuzzer to also catch expected UnsupportedOperationException.

Keycloak: Catch expected UnsupportedOperationException

---

projects/keycloak/JweFuzzer.java

This PR fixes expected IllegalStateException discovered in https://issues.oss-fuzz.com/u/7/issues/371683507.

Keycloak: Catch expected IllegalStateException from invalid JWE String

---

projects/keycloak/TokenVerifierFuzzer.java

This PR fixes the problem that unexpected NPE is thrown whenhandling malformed webtoken.

Keycloak: Fix unexpected NPE

---

projects/kubeedge/build.sh

KubeEdge will move viaduct path to https://github.com/kubeedge/kubeedge/tree/master/pkg in https://github.com/kubeedge/kubeedge/pull/5907, this PR updates the corresponding viaduct path.

KubeEdge: update viaduct fuzzer path

---

projects/kubeedge/build.sh
projects/kubeedge/lane_fuzzer.go

KubeEdge will move viaduct path to https://github.com/kubeedge/kubeedge/tree/master/pkg in https://github.com/kubeedge/kubeedge/pull/5907, this PR fix the corresponding viaduct path.

KubeEdge: Fix viaduct path

---

README.md

The link to handbook-fuzzing.pdf is **broken** in the README.md.
It is fixed now by pointing to the correct link.
Also, there were a few typos which are corrected in README.md.

README.md: Fix broken handbook link, correct minor typos

---

projects/kubernetes/roundtrip.go
projects/kubernetes/validation_fuzzer.go

Hi everyone,
During the Security Audit of Kubernetes Subprojects, we noticed that the current build of Kubernetes fuzzers on OSS-Fuzz is failing. [1]
In particular, for `roundtrip.go` Kubernetes deprecated the use of google's `go-fuzz` library in favor of `sigs.k8s.io/randfill`.
While for `validation_fuzzer.go` the signature of some API changed on Kubernetes side.
This PR fixes both of them, restoring a successful fuzzers build.
[1] https://introspector.oss-fuzz.com/project-profile?project=kubernetes
[2] https://oss-fuzz-build-logs.storage.googleapis.com/log-7522d37e-f347-452c-b00d-cb92498e74f0.txt

Fix Kubernetes fuzzers that are failing

---

projects/cilium/OnData_fuzzer.go
projects/cilium/build.sh

The current test utils call logrus.Fatalf, which causes the fuzzer to exit with status code 1, which breaks the test harness. See cilium/proxy#1487 and https://github.com/cilium/cilium/pull/40728
Also removing some more unneeded fuzzers.

cilium: Override proxylib.LogFatal
